package com.example.util

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    HINDI("hi", "Hindi", "हिन्दी"),
    PUNJABI("pa", "Punjabi", "ਪੰਜਾਬੀ"),
    SPANISH("es", "Spanish", "Español")
}

object AppStrings {
    fun get(key: String, lang: AppLanguage): String {
        return translations[lang]?.get(key)
            ?: translations[AppLanguage.ENGLISH]?.get(key)
            ?: key
    }

    private val en = mapOf(
        "nav_home" to "Home",
        "nav_search" to "Search",
        "nav_library" to "Your Library",
        "nav_equalizer" to "Equalizer",
        "nav_stats" to "Equalizer",
        "nav_settings" to "Settings",
        "greeting_morning" to "Good morning",
        "greeting_afternoon" to "Good afternoon",
        "greeting_evening" to "Good evening",
        "made_for_you" to "Made For You",
        "recently_played" to "Jump Back In",
        "trending_now" to "Trending Today",
        "recommended" to "Recommended Hits",
        "discover_weekly" to "Weekly Mix",
        "offline_mode" to "Offline Mode",
        "offline_banner" to "Listening in Offline Mode (Downloaded only)",
        "downloaded_music" to "Downloaded Songs",
        "favorites" to "Liked Songs",
        "all_songs" to "All Songs",
        "create_playlist" to "Create Playlist",
        "playlist_name" to "Playlist Name",
        "playlist_desc" to "Description (optional)",
        "cancel" to "Cancel",
        "create" to "Create",
        "search_hint" to "Search songs, artists, genres...",
        "audio_quality" to "Audio Quality",
        "streaming_quality" to "Streaming Quality",
        "download_quality" to "Download Quality",
        "equalizer" to "Equalizer",
        "now_playing" to "Now Playing",
        "lyrics" to "Lyrics",
        "no_lyrics" to "Lyrics not available for this song",
        "share" to "Share Song",
        "share_sheet_title" to "Share this track with friends",
        "download" to "Download",
        "downloaded" to "Downloaded",
        "analytics_title" to "Your Music Stats & Insights",
        "total_time" to "Minutes Listened",
        "songs_played" to "Songs Played",
        "top_artists" to "Top Artists",
        "top_genres" to "Top Genres",
        "google_account" to "Google Account",
        "signed_in_as" to "Signed in as",
        "sign_in_google" to "Sign In with Google",
        "sign_out" to "Sign Out",
        "data_saver" to "Data Saver Mode",
        "crossfade" to "Crossfade (seconds)",
        "volume_normal" to "Normalize Volume",
        "dark_mode" to "Dark Mode",
        "pure_black" to "Pure OLED Black",
        "language" to "App Language",
        "queue" to "Queue",
        "add_to_playlist" to "Add to Playlist",
        "delete_playlist" to "Delete Playlist",
        "empty_downloads" to "No downloaded songs yet. Tap the download icon to listen offline!",
        "empty_playlists" to "No playlists created yet.",
        "storage_used" to "Offline Storage Used"
    )

    private val hi = mapOf(
        "nav_home" to "होम",
        "nav_search" to "खोजें",
        "nav_library" to "लाइब्रेरी",
        "nav_equalizer" to "इक्वलाइज़र",
        "nav_stats" to "इक्वलाइज़र",
        "nav_settings" to "सेटिंग्स",
        "greeting_morning" to "शुभ प्रभात",
        "greeting_afternoon" to "शुभ दोपहर",
        "greeting_evening" to "शुभ संध्या",
        "made_for_you" to "खास आपके लिए",
        "recently_played" to "हाल ही में सुने गए",
        "trending_now" to "आज का ट्रेंडिंग",
        "recommended" to "सुझाए गए गाने",
        "discover_weekly" to "साप्ताहिक मिक्स",
        "offline_mode" to "ऑफलाइन मोड",
        "offline_banner" to "ऑफलाइन मोड सक्रिय है (केवल डाउनलोड किए गाने)",
        "downloaded_music" to "डाउनलोड किए गए गाने",
        "favorites" to "पसंदीदा गाने",
        "all_songs" to "सभी गाने",
        "create_playlist" to "प्लेलिस्ट बनाएं",
        "playlist_name" to "प्लेलिस्ट का नाम",
        "playlist_desc" to "विवरण (वैकल्पिक)",
        "cancel" to "रद्द करें",
        "create" to "बनाएं",
        "search_hint" to "गाने, कलाकार, शैली खोजें...",
        "audio_quality" to "म्यूजिक क्वालिटी",
        "streaming_quality" to "स्ट्रीमिंग क्वालिटी",
        "download_quality" to "डाउनलोड क्वालिटी",
        "equalizer" to "इक्वलाइज़र",
        "now_playing" to "अब बज रहा है",
        "lyrics" to "गाने के बोल (Lyrics)",
        "no_lyrics" to "इस गाने के बोल उपलब्ध नहीं हैं",
        "share" to "गाना शेयर करें",
        "share_sheet_title" to "दोस्तों के साथ शेयर करें",
        "download" to "डाउनलोड करें",
        "downloaded" to "डाउनलोड हो गया",
        "analytics_title" to "आपके संगीत आंकड़े",
        "total_time" to "सुने गए कुल मिनट",
        "songs_played" to "सुने गए गाने",
        "top_artists" to "पसंदीदा कलाकार",
        "top_genres" to "पसंदीदा शैलियां",
        "google_account" to "गूगल खाता",
        "signed_in_as" to "के रूप में लॉग-इन हैं",
        "sign_in_google" to "गूगल से साइन-इन करें",
        "sign_out" to "लॉग आउट",
        "data_saver" to "डेटा सेवर मोड",
        "crossfade" to "क्रॉसफ़ेड (सेकंड)",
        "volume_normal" to "आवाज़ सामान्य करें",
        "dark_mode" to "डार्क मोड",
        "pure_black" to "प्योर OLED ब्लैक",
        "language" to "ऐप भाषा",
        "queue" to "कतार (Queue)",
        "add_to_playlist" to "प्लेलिस्ट में जोड़ें",
        "delete_playlist" to "प्लेलिस्ट हटाएं",
        "empty_downloads" to "अभी कोई गाना डाउनलोड नहीं है। ऑफलाइन सुनने के लिए डाउनलोड बटन दबाएं!",
        "empty_playlists" to "अभी कोई प्लेलिस्ट नहीं बनाई गई।",
        "storage_used" to "उपयोग किया गया स्पेस"
    )

    private val pa = mapOf(
        "nav_home" to "ਹੋਮ",
        "nav_search" to "ਖੋਜੋ",
        "nav_library" to "ਲਾਇਬ੍ਰੇਰੀ",
        "nav_equalizer" to "ਇਕੁਅਲਾਈਜ਼ਰ",
        "nav_stats" to "ਇਕੁਅਲਾਈਜ਼ਰ",
        "nav_settings" to "ਸੈਟਿੰਗਾਂ",
        "greeting_morning" to "ਸ਼ੁਭ ਸਵੇਰ",
        "greeting_afternoon" to "ਸ਼ੁਭ ਦੁਪਹਿਰ",
        "greeting_evening" to "ਸ਼ੁਭ ਸ਼ਾਮ",
        "made_for_you" to "ਤੁਹਾਡੇ ਲਈ ਖਾਸ",
        "recently_played" to "ਹਾਲ ਹੀ ਵਿੱਚ ਸੁਣੇ",
        "trending_now" to "ਟਰੈਂਡਿੰਗ ਟਰੈਕਸ",
        "recommended" to "ਸਿਫਾਰਿਸ਼ੀ ਗੀਤ",
        "discover_weekly" to "ਹਫ਼ਤਾਵਾਰੀ ਮਿਕਸ",
        "offline_mode" to "ਆਫਲਾਈਨ ਮੋਡ",
        "offline_banner" to "ਆਫਲਾਈਨ ਮੋਡ ਚਾਲੂ ਹੈ (ਸਿਰਫ ਡਾਊਨਲੋਡ ਗਾਣੇ)",
        "downloaded_music" to "ਡਾਊਨਲੋਡ ਕੀਤੇ ਗੀਤ",
        "favorites" to "ਪਸੰਦੀਦਾ ਗੀਤ",
        "all_songs" to "ਸਾਰੇ ਗੀਤ",
        "create_playlist" to "ਪਲੇਲਿਸਟ ਬਣਾਓ",
        "playlist_name" to "ਪਲੇਲਿਸਟ ਦਾ ਨਾਂ",
        "playlist_desc" to "ਵੇਰਵਾ (ਵਿਕਲਪਿਕ)",
        "cancel" to "ਰੱਦ ਕਰੋ",
        "create" to "ਬਣਾਓ",
        "search_hint" to "ਗਾਣੇ, ਕਲਾਕਾਰ ਖੋਜੋ...",
        "audio_quality" to "ਆਡੀਓ ਕੁਆਲਿਟੀ",
        "streaming_quality" to "ਸਟ੍ਰੀਮਿੰਗ ਕੁਆਲਿਟੀ",
        "download_quality" to "ਡਾਊਨਲੋਡ ਕੁਆਲਿਟੀ",
        "equalizer" to "ਇਕੁਅਲਾਈਜ਼ਰ",
        "now_playing" to "ਹੁਣ ਵੱਜ ਰਿਹਾ",
        "lyrics" to "ਬੋਲ (Lyrics)",
        "no_lyrics" to "ਬੋਲ ਉਪਲਬਧ ਨਹੀਂ ਹਨ",
        "share" to "ਗੀਤ ਸ਼ੇਅਰ ਕਰੋ",
        "share_sheet_title" to "ਦੋਸਤਾਂ ਨਾਲ ਗੀਤ ਸਾਂਝਾ ਕਰੋ",
        "download" to "ਡਾਊਨਲੋਡ",
        "downloaded" to "ਡਾਊਨਲੋਡ ਹੋ ਗਿਆ",
        "analytics_title" to "ਤੁਹਾਡੇ ਸੰਗੀਤ ਅੰਕੜੇ",
        "total_time" to "ਕੁੱਲ ਸੁਣੇ ਮਿੰਟ",
        "songs_played" to "ਵਜਾਏ ਗਏ ਗੀਤ",
        "top_artists" to "ਮੁੱਖ ਕਲਾਕਾਰ",
        "top_genres" to "ਮੁੱਖ ਸ਼ੈਲੀਆਂ",
        "google_account" to "ਗੂਗਲ ਅਕਾਊਂਟ",
        "signed_in_as" to "ਲੌਗ-ਇਨ ਵਜੋਂ",
        "sign_in_google" to "ਗੂਗਲ ਨਾਲ ਲੌਗਇਨ ਕਰੋ",
        "sign_out" to "ਸਾਈਨ ਆਊਟ",
        "data_saver" to "ਡੇਟਾ ਸੇਵਰ",
        "crossfade" to "ਕ੍ਰਾਸਫੇਡ",
        "volume_normal" to "ਵਾਲੀਅਮ ਸਾਧਾਰਨ",
        "dark_mode" to "ਡਾਰਕ ਮੋਡ",
        "pure_black" to "ਓਲੈੱਡ ਬਲੈਕ",
        "language" to "ਐਪ ਭਾਸ਼ਾ",
        "queue" to "ਕਤਾਰ",
        "add_to_playlist" to "ਪਲੇਲਿਸਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ",
        "delete_playlist" to "ਪਲੇਲਿਸਟ ਹਟਾਓ",
        "empty_downloads" to "ਕੋਈ ਗੀਤ ਡਾਊਨਲੋਡ ਨਹੀਂ ਹੈ। ਆਫਲਾਈਨ ਸੁਣਨ ਲਈ ਡਾਊਨਲੋਡ ਕਰੋ!",
        "empty_playlists" to "ਕੋਈ ਪਲੇਲਿਸਟ ਨਹੀਂ ਹੈ।",
        "storage_used" to "ਸਟੋਰੇਜ ਵਰਤੀ ਗਈ"
    )

    private val es = mapOf(
        "nav_home" to "Inicio",
        "nav_search" to "Buscar",
        "nav_library" to "Tu Biblioteca",
        "nav_equalizer" to "Ecualizador",
        "nav_stats" to "Ecualizador",
        "nav_settings" to "Ajustes",
        "greeting_morning" to "Buenos días",
        "greeting_afternoon" to "Buenas tardes",
        "greeting_evening" to "Buenas noches",
        "made_for_you" to "Hecho para ti",
        "recently_played" to "Escuchado recientemente",
        "trending_now" to "Tendencias de hoy",
        "recommended" to "Canciones recomendadas",
        "discover_weekly" to "Mix Semanal",
        "offline_mode" to "Modo sin conexión",
        "offline_banner" to "Modo sin conexión activado (Solo descargadas)",
        "downloaded_music" to "Canciones descargadas",
        "favorites" to "Tus me gusta",
        "all_songs" to "Todas las canciones",
        "create_playlist" to "Crear lista de reproducción",
        "playlist_name" to "Nombre de la lista",
        "playlist_desc" to "Descripción (opcional)",
        "cancel" to "Cancelar",
        "create" to "Crear",
        "search_hint" to "Buscar canciones, artistas...",
        "audio_quality" to "Calidad de audio",
        "streaming_quality" to "Calidad de streaming",
        "download_quality" to "Calidad de descarga",
        "equalizer" to "Ecualizador",
        "now_playing" to "Reproduciendo ahora",
        "lyrics" to "Letras",
        "no_lyrics" to "Letras no disponibles",
        "share" to "Compartir canción",
        "share_sheet_title" to "Compartir con amigos",
        "download" to "Descargar",
        "downloaded" to "Descargado",
        "analytics_title" to "Tus Estadísticas Musicales",
        "total_time" to "Minutos escuchados",
        "songs_played" to "Canciones reproducidas",
        "top_artists" to "Artistas principales",
        "top_genres" to "Géneros principales",
        "google_account" to "Cuenta de Google",
        "signed_in_as" to "Conectado como",
        "sign_in_google" to "Iniciar sesión con Google",
        "sign_out" to "Cerrar sesión",
        "data_saver" to "Ahorro de datos",
        "crossfade" to "Crossfade (segundos)",
        "volume_normal" to "Normalizar volumen",
        "dark_mode" to "Modo oscuro",
        "pure_black" to "Negro OLED puro",
        "language" to "Idioma de la app",
        "queue" to "Cola de reproducción",
        "add_to_playlist" to "Añadir a lista",
        "delete_playlist" to "Eliminar lista",
        "empty_downloads" to "Sin canciones descargadas. ¡Descarga para escuchar sin conexión!",
        "empty_playlists" to "No hay listas creadas.",
        "storage_used" to "Espacio utilizado"
    )

    private val translations = mapOf(
        AppLanguage.ENGLISH to en,
        AppLanguage.HINDI to hi,
        AppLanguage.PUNJABI to pa,
        AppLanguage.SPANISH to es
    )
}
